
services:
  mongodb:
    image: mongo:7.0
    container_name: aps-chat-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: chatapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - aps-chat-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aps-chat-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/chatapp
      JWT_SECRET: ${JWT_SECRET:-mySecretKeyForJWTToken123456789012345678901234567890}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - aps-chat-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  aps-chat-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
